name: API dan UI Web CI/CD Pipeline

# Trigger workflow pada push ke branch manapun atau pada pull request ke main/master
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout kode dari repository
    - name: Checkout kode
      uses: actions/checkout@v3
    
    # Setup Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Compile dan build dengan Maven
    - name: Build dengan Maven
      run: mvn -B package --file pom.xml
    
    # Jalankan API tests
    - name: Run API tests
      run: mvn test -Dtest=ApiTest*
    
    # Siapkan driver untuk UI tests
    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@v2
    
    # Jalankan UI tests
    - name: Run UI tests
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        mvn test -Dtest=UiTest*
    
    # Upload hasil test report sebagai artifact
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/failsafe-reports/
          target/site/