name: API dan UI Web CI/CD Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout kode
      uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build dengan Maven
      run: mvn clean compile
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    
    - name: Run all tests
      env:
        DISPLAY: :99
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        mvn test -Dheadless=true
      continue-on-error: true
    
    - name: Generate Test Report
      if: always()
      run: |
        mvn surefire-report:report-only
        mvn site -DgenerateReports=false
      continue-on-error: true
    
    - name: Save test results
      if: always()
      run: |
        mkdir -p test-results
        cp -R target/surefire-reports/* test-results/ || true
        echo "Test results saved"
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/
        retention-days: 30
