name: API dan UI Web CI/CD Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify-setup:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout kode dari repository
    - name: Checkout kode
      uses: actions/checkout@v3
    
    # Setup Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # Verifikasi struktur proyek
    - name: Verify Project Structure
      run: |
        echo "Current directory content:"
        ls -la
        echo "GitHub Actions workflow is running correctly!"
        
    # Jika pom.xml sudah ada, verifikasi dengan Maven
    - name: Check if pom.xml exists
      id: check_pom
      run: |
        if [ -f "pom.xml" ]; then
          echo "pom_exists=true" >> $GITHUB_OUTPUT
          echo "pom.xml exists!"
        else
          echo "pom_exists=false" >> $GITHUB_OUTPUT
          echo "pom.xml does not exist yet. This is normal for a new project."
        fi
    
    # Jalankan Maven validate hanya jika pom.xml ada
    - name: Validate dengan Maven
      if: steps.check_pom.outputs.pom_exists == 'true'
      run: mvn -B validate --file pom.xml
      continue-on-error: true
