name: API dan UI Web CI/CD Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout kode dari repository
    - name: Checkout kode
      uses: actions/checkout@v3
    
    # Setup Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Membersihkan dan mem-build project dengan Maven
    - name: Build dengan Maven
      run: mvn clean compile
      
    # Jalankan API tests
    - name: Run API tests
      run: mvn test -Dgroups=api
      continue-on-error: true
    
    # Setup headless Chrome untuk UI tests
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    # Jalankan UI tests dengan headless Chrome
    - name: Run UI tests
      env:
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -screen 0 1920x1080x24 &
        mvn test -Dgroups=ui -Dheadless=true
      continue-on-error: true
    
    # Generate Allure report
    - name: Generate Allure Report
      run: mvn allure:report
    
    # Mengumpulkan dan mengupload report sebagai artifacts
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/allure-results/
          target/site/allure-maven-plugin/
          target/site/
