name: API dan UI Web CI/CD Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout kode dari repository
    - name: Checkout kode
      uses: actions/checkout@v3
    
    # Setup Java environment
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Membersihkan dan mem-build project dengan Maven
    - name: Build dengan Maven
      run: mvn clean compile
      
    # Setup headless Chrome untuk UI tests
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    # Install Xvfb for headless operation
    - name: Install Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    
    # Run all tests
    - name: Run all tests
      env:
        DISPLAY: :99
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        mvn test -Dheadless=true
      continue-on-error: true
    
    # Generate test report
    - name: Generate Test Report
      if: always()
      run: |
        mvn surefire-report:report-only
        mvn site -DgenerateReports=false
      continue-on-error: true
    
    # Test summary
    - name: Test Results Summary
      if: always()
      run: |
        echo "### Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -d "target/surefire-reports" ]; then
          echo "✅ Tests executed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ No test reports found" >> $GITHUB_STEP_SUMMARY
        fi
