name: API dan UI Web CI/CD Pipeline

# Trigger workflow pada push ke branch manapun atau pada pull request ke main/master
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout kode dari repository
    - name: Checkout kode
      uses: actions/checkout@v3
    
    # Setup Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Verifikasi struktur proyek
    - name: Verify Project Structure
      run: |
        echo "Current directory content:"
        ls -la
        echo "GitHub Actions workflow is running correctly!"
    
    # Jika pom.xml sudah ada, jalankan Maven
    - name: Check if pom.xml exists
      id: check_pom
      run: |
        if [ -f "pom.xml" ]; then
          echo "pom_exists=true" >> $GITHUB_OUTPUT
        else
          echo "pom_exists=false" >> $GITHUB_OUTPUT
        fi
    
    # Jalankan Maven hanya jika pom.xml ada
    - name: Build dengan Maven
      if: steps.check_pom.outputs.pom_exists == 'true'
      run: mvn -B package --file pom.xml
      continue-on-error: true
    
    # Upload hasil test report sebagai artifact (menggunakan v2 sebagai alternatif)
    - name: Upload test reports
      if: steps.check_pom.outputs.pom_exists == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/failsafe-reports/
          target/site/
        if-no-files-found: ignore