name: Web UI Tests CI/CD Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web-ui-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Setup Java environment
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Build project with Maven
    - name: Build with Maven
      run: mvn clean compile
    
    # Setup headless Chrome for UI tests
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    # Install Xvfb for headless operation
    - name: Install Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    
    # Run Web UI tests
    - name: Run Web UI tests
      env:
        DISPLAY: :99
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        mvn test -Dgroups=ui -Dheadless=true
      continue-on-error: true
    
    # Generate test report
    - name: Generate Test Report
      if: always()
      run: |
        mvn surefire-report:report-only || true
        mvn site -DgenerateReports=false || true
      continue-on-error: false
    
    # Generate Allure Report
    - name: Generate Allure Report
      if: always()
      run: |
        mvn allure:report || true
      continue-on-error: false
    
    # Upload test results
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: web-ui-test-results
        path: |
          target/surefire-reports/
          target/site/
        retention-days: 30
    
    # Upload Allure reports
    - name: Upload Allure Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: web-ui-allure-reports
        path: |
          target/site/allure-maven-plugin/
        retention-days: 30
    
    # Upload logs
    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: web-ui-logs
        path: |
          logs/
        retention-days: 7
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: target/site/allure-maven-plugin/
        destination_dir: web-ui-tests
    
    # Test summary
    - name: Test Results Summary
      if: always()
      run: |
        echo "### Web UI Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -d "target/surefire-reports" ]; then
          total_tests=$(grep -oP 'tests="\K[0-9]+' target/surefire-reports/TEST-*.xml | paste -sd+ | bc)
          failed_tests=$(grep -oP 'failures="\K[0-9]+' target/surefire-reports/TEST-*.xml | paste -sd+ | bc)
          skipped_tests=$(grep -oP 'skipped="\K[0-9]+' target/surefire-reports/TEST-*.xml | paste -sd+ | bc)
          
          echo "✅ Total tests: $total_tests" >> $GITHUB_STEP_SUMMARY
          echo "❌ Failed tests: $failed_tests" >> $GITHUB_STEP_SUMMARY  
          echo "⏭️ Skipped tests: $skipped_tests" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ No test reports found" >> $GITHUB_STEP_SUMMARY
        fi
